Fix incubator in NuRV service example (#51)
- Fix of CORBA ORB not working and minor changes
- Adds missing dependencies

diff --git a/digital_twins/incubator-NuRV-monitor-service/lifecycle/create b/digital_twins/incubator-NuRV-monitor-service/lifecycle/create
--- a/digital_twins/incubator-NuRV-monitor-service/lifecycle/create
+++ b/digital_twins/incubator-NuRV-monitor-service/lifecycle/create
@@ -1,6 +1,31 @@
 #!/bin/bash
 
-apt update
+set -e # Exit on command failure
+
+apt_updated=false
+
+check_binary() {
+    if dpkg -l "$1" &> /dev/null; then
+        echo "$1 is installed."
+    else
+        echo "$1 is not installed. Installing."
+        if [ "$apt_updated" = false ]; then
+            sudo apt update
+            sudo apt upgrade
+            apt_updated=true
+        fi
+        sudo apt install "${2:-$1}" # Install argument 2 if provided, otherwise 1
+    fi
+}
+
+echo "Checking dependencies"
+
+# Install stuff
+check_binary "python3"
+check_binary "python3-pip"
+check_binary "python3-venv"
+pip install wheel
+
 cd "$(dirname "${BASH_SOURCE[0]}")"
 # install packages
 cd "../$(dirname "${BASH_SOURCE[0]}")"
